# Generated by Django 2.2.15 on 2020-08-23 03:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidPipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'pipes',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('destination', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_destination', to='entities.Location')),
                ('origin', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_origin', to='entities.Location')),
                ('pipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement', to='entities.CovidPipe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='covidpipe',
            name='last_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_movement', to='entities.Movement'),
        ),
    ]
