# Generated by Django 2.2.15 on 2020-08-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_covidpipe_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
