# Generated by Django 2.2.15 on 2020-08-24 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_auto_20200824_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidpipe',
            name='last_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_movement', to='entities.Movement'),
        ),
    ]
