# Generated by Django 2.2.15 on 2020-08-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_auto_20200824_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movement',
            name='date_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movement',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'A ENVIAR'), (2, 'ENVIADO')], default=1),
        ),
    ]
