# Generated by Django 2.2.15 on 2020-08-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_auto_20200825_0553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='covidpipe',
            options={'ordering': ['-name'], 'verbose_name_plural': 'pipes'},
        ),
    ]
